CRISIS_KEYWORDS_RU = [
    "хочу умереть",
    "не хочу жить",
    "покончить с собой",
    "суицид",
    "самоубийство",
    "повеситься",
    "повешусь",
    "прыгну с",
    "спрыгну с",
    "наглотаюсь таблеток",
    "перережу вены",
    "вскрою вены",
    "жизнь не имеет смысла",
    "всем будет лучше без меня",
    "никому не нужен",
    "никому не нужна",
    "хочу исчезнуть",
    "лучше бы меня не было",
    "устал жить",
    "устала жить",
    "нет смысла жить",
    "зачем я живу",
    "конец всему",
    "убить себя",
    "убью себя",
    "не вижу выхода",
    "не вижу смысла",
    "порезать себя",
    "причинить себе боль",
    "самоповреждение",
]

CRISIS_KEYWORDS_EN = [
    "want to die",
    "kill myself",
    "end my life",
    "suicide",
    "suicidal",
    "hang myself",
    "jump off",
    "slit my wrists",
    "cut myself",
    "overdose",
    "no reason to live",
    "better off dead",
    "better off without me",
    "can't go on",
    "self harm",
    "self-harm",
    "want to disappear",
    "no way out",
    "end it all",
]

ALL_CRISIS_KEYWORDS = CRISIS_KEYWORDS_RU + CRISIS_KEYWORDS_EN
